// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.2
// source: event-schemas/otp.proto

package event_schemas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OtpGenerated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *EventHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpGenerated) Reset() {
	*x = OtpGenerated{}
	mi := &file_event_schemas_otp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpGenerated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpGenerated) ProtoMessage() {}

func (x *OtpGenerated) ProtoReflect() protoreflect.Message {
	mi := &file_event_schemas_otp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpGenerated.ProtoReflect.Descriptor instead.
func (*OtpGenerated) Descriptor() ([]byte, []int) {
	return file_event_schemas_otp_proto_rawDescGZIP(), []int{0}
}

func (x *OtpGenerated) GetHeader() *EventHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *OtpGenerated) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OtpGenerated) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_event_schemas_otp_proto protoreflect.FileDescriptor

var file_event_schemas_otp_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2f,
	0x6f, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f, 0x74, 0x70, 0x1a, 0x1a,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2f, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x0c, 0x4f, 0x74,
	0x70, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x73, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_event_schemas_otp_proto_rawDescOnce sync.Once
	file_event_schemas_otp_proto_rawDescData = file_event_schemas_otp_proto_rawDesc
)

func file_event_schemas_otp_proto_rawDescGZIP() []byte {
	file_event_schemas_otp_proto_rawDescOnce.Do(func() {
		file_event_schemas_otp_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_schemas_otp_proto_rawDescData)
	})
	return file_event_schemas_otp_proto_rawDescData
}

var file_event_schemas_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_schemas_otp_proto_goTypes = []any{
	(*OtpGenerated)(nil), // 0: otp.OtpGenerated
	(*EventHeader)(nil),  // 1: shared.EventHeader
}
var file_event_schemas_otp_proto_depIdxs = []int32{
	1, // 0: otp.OtpGenerated.header:type_name -> shared.EventHeader
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_schemas_otp_proto_init() }
func file_event_schemas_otp_proto_init() {
	if File_event_schemas_otp_proto != nil {
		return
	}
	file_event_schemas_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_schemas_otp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_schemas_otp_proto_goTypes,
		DependencyIndexes: file_event_schemas_otp_proto_depIdxs,
		MessageInfos:      file_event_schemas_otp_proto_msgTypes,
	}.Build()
	File_event_schemas_otp_proto = out.File
	file_event_schemas_otp_proto_rawDesc = nil
	file_event_schemas_otp_proto_goTypes = nil
	file_event_schemas_otp_proto_depIdxs = nil
}
